// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmzujecowiwmvdahycwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tenVqZWNvd2l3bXZkYWh5Y3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTU2NjMsImV4cCI6MjA2NTg5MTY2M30.qxJJvMHtO6pO112_fDspT0jKQoJcReOjqIA5SWiHsQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);